### PR TITLE
Add msgpack decoder

### PR DESCRIPTION
**Pull request by toelke**
Hi,

I am not experienced in Java programming so please excuse any stupid mistake.

We needed a way to decode msgpack-buffers (https://msgpack.org/), so here is a decoder for that.

Cheers,
Philipp

### CODE REVIEW

**Comment by janusw** [comment]
Nice! I hope this gets merged soon and makes it into a future mqtt.fx release!

Is there a way to test it with the current mqtt.fx version (1.7.1)?

**Comment by toelke** [comment]
I use this dockerfile to build a mqtt.fx:
```
FROM gradle:jdk12 AS builder

RUN mkdir src
WORKDIR src
RUN git clone --branch add-msgpack-decoder https://github.com/fos4X/mqttfx-payload-decoders.git .
RUN gradle jar

FROM debian:buster

RUN apt update && apt install -y wget openjfx libxslt1.1 && rm -rf /var/lib/apt/lists
RUN ln -s /bin/true /usr/bin/xdg-desktop-menu && wget http://www.jensd.de/apps/mqttfx/1.7.1/mqttfx-1.7.1-64bit.deb && dpkg -i *.deb && rm *.deb

COPY --from=builder /home/gradle/src/build/libs/mqttfx-payload-decoders-1.6.0.jar /opt/MQTTfx/app/lib/mqttfx-payload-decoders-1.6.0.jar

ADD https://repo1.maven.org/maven2/org/msgpack/msgpack-core/0.8.17/msgpack-core-0.8.17.jar /opt/MQTTfx/app/lib/
RUN sed -i -e 's,\(^app.classpath.*$\),\1:lib/msgpack-core-0.8.17.jar,' /opt/MQTTfx/app/MQTTfx.cfg
```

And then run this container with `-e DISPLAY=<host>` where host can be `host.docker.internal` on windows. You need to be running an X-Server like https://sourceforge.net/projects/vcxsrv/ .

**Comment by janusw** [comment]
I'm on a native Linux, so I just built the mqttfx-payload-decoders from your branch via `gradle jar`, after that copied `mqttfx-payload-decoders-1.6.0.jar` and `msgpack-core-0.8.17.jar` into `/opt/MQTTfx/app/lib` and adjusted MQTTfx.cfg (as shown in your dockerfile).

Then firing up MQTT.fx gives me a neatly working MsgPack decoder. Pretty cool :smile: 

Btw, I couldn't even build the mqttfx-payload-decoders master branch without your modifications, because javafx is not found :frowning: 

So, yes, I strongly support this pull request :+1:

**Comment by toelke** [comment]
Yes, two of my commits are necessary to get the repository to build; perhaps I should have created a second pull-request for those :-)

**Comment by janusw** [comment]
> Yes, three of my commits are necessary to get the repository to build; perhaps I should have created a second pull-request for those :-)

All the more reason to merge this one ;)

In any case, thanks for the great work! As mentioned above, the decoder works like a charm. I think the new functionality certainly justifies a new release of MQTT.fx ...

**Comment by janusw** [comment]
One small bit of feedback: You should probably update README.md to list the new decoder. Or maybe the maintainer will do that ...?

**Comment by toelke** [comment]
Done

**Comment by janusw** [comment]
@Jerady Would you consider merging this branch? I have tested the new msgpack decoder and can confirm that it works as advertised ...

**Comment by toelke** [comment]
Unfortunately, I am no longer member of @polytechas, so I cannot solve the merge conflicts.

**Pull request merged**
